name: PyCaret AutoML Git Action
on: 
  push :
    branches: [ master ]  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PyCaret AutoML Git Action
        id: model
        uses: pycaret/pycaret-git-actions@v9.0
      - name: Upload model.pkl
        uses: actions/upload-artifact@v2
        with: 
          name: my-artifact
          path: model.pkl
