name: PyCaret AutoML Git Action
on: 
  push :
    branches: [ master ]  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PyCaret AutoML Git Action
        id: model
        uses: pycaret/pycaret-git-actions@v13.0
        with:
          myInput: "Purchase"
      - name: Upload model.pkl
        uses: actions/upload-artifact@v2
        with: 
          name: model
          path: model.pkl
      - name: Upload logs.log
        uses: actions/upload-artifact@v2
        with: 
          name: logs
          path: logs.log
      - name: Upload juice1_logs.csv
        uses: actions/upload-artifact@v2
        with: 
          name: experiment-logs
          path: exp1_logs.csv
